name          'yo61-user_group'
version       '0.1.0'
source        'https://github.com/yo61/puppet-user_group'
author        'yo61'
license       'Apache 2.0'
summary       'Convenience module to create users and groups'
description   ''
project_page  'https://github.com/yo61/puppet-user_group'

dependency 'puppetlabs/stdlib'
